apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-driver-deploy
  labels:
    app: cpp-driver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cpp-driver
  template:
    metadata:
      labels:
        app: cpp-driver
    spec:
      containers:
        - name: cpp-driver
          image: bblfsh/cpp-driver
          ports:
            - containerPort: 9432
apiVersion: v1
kind: Service
metadata:
  name: cpp-driver-svc
spec:
  selector:
    app: cpp-driver
  ports:
    - protocol: TCP
      port: 9432
      targetPort: 9432
  type: LoadBalancer
